# Generated by Django 5.0 on 2023-12-09 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_joined_date_members_phone_alter_members_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
